name: diagonal
description: Create diagonal clipped widgets easily.
version: 1.0.0
author: Figen Güngör <figengungor1@gmail.com>
homepage: https://github.com/figengungor/diagonal

environment:
  sdk: ">=1.19.0 <2.0.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
